name: 'Backend Continuous Integration'
on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'starter/frontend/**'
  workflow_dispatch:

env:
  # Set Node.js Version
  NODE_VERSION: '18.x'

jobs:
  lintApplication:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code to the runner
        run: actions/checkout@v3
      - name: Install pipenv
        run: pipenv install
      - name: Test pipenv
        run: pipenv run lint
  testApplication:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code to the runner
        run: actions/checkout@v3
      - name: Install pipenv
        run: pipenv install
      - name: Test pipenv
        run: pipenv run test
  buildApplication:
    needs: [lintApplication, testApplication]
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code to the runner
        run: actions/checkout@v3
      - name: Install pipenv
        run: pipenv install
      - name: Run application
        run: pipenv run serve
      - name: Build Docker image
        run: docker build --tag mp-backend:latest .
        working-directory: ./starter/backend
      - name: Run Docker image
        run: docker run -p 5000:5000 --name mp-backend -d mp-backend
        working-directory: ./starter/backend