name: 'Frontend Continuous Integration'
on:
  pull_request:
    branches:
      - 'main'
    # paths:
    #   - 'starter/frontend/**'
  workflow_dispatch:

jobs:
  lintApplication:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: starter/frontend
    steps:
      - name: Check out the code to the runner
        uses: actions/checkout@v3
      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: ${{github.workspace}}/starter/frontend/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npx eslint --fix .
  testApplication:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: starter/frontend
    steps:
      - name: Check out the code to the runner
        uses: actions/checkout@v3
      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: ${{github.workspace}}/starter/frontend/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: CI=true npm test
  buildApplication:
    needs: [lintApplication, testApplication]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: starter/frontend
    steps:
      - name: Check out the code to the runner
        uses: actions/checkout@v3

      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: ${{github.workspace}}/starter/frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build Docker image
        run: docker build --build-arg=REACT_APP_MOVIE_API_URL=http://localhost:5000 --tag=mp-frontend:latest .
      
      - name: Run Docker image
        run: docker run --name mp-frontend -p 3000:3000 -d mp-frontend

      - name: Stop the application
        run: docker stop mp-frontend
